#!/usr/bin/python
# coding=utf-8

import re, urllib, sys
from generic_transform import * 

e_type,e_values,params = get_from_args()


website = e_values["value"]

result=[]

regex = re.compile('([a-zA-Z][\w\-\._]+?@([a-zA-Z]([\w\.\-_]+?\.){1,3}[\w\.]{2,5}))\W',re.VERBOSE)
url = urllib.urlopen(website)

codehtml = url.readlines()
for line in codehtml:
    emails = regex.findall(line)
    for email in emails:
        res = email[0]
        if res not in result:
            result.append(res)
            val = {}
            val["value"] = unicode(res, 'utf-8')
            val["verified"] = unicode("False", 'utf-8')
            write_result("email-address", val)
            sys.stdout.flush()

