#!/usr/bin/python
# coding=utf-8

import urllib, re, sys
from generic_transform import * 

e_type,e_values,params = get_from_args()

search = e_values["value"].replace(' ','+')

if 'search-world' in e_values:
    search=search+'+'+e_values['search-world']

if 'nickname' in e_values:
    search=search+'+'+e_values['nickname']


regexB =re.compile('<hr><pre>.*?</a>.*?>(.*?)</pre>',re.VERBOSE|re.DOTALL)
regexM = re.compile('&lt;(.*?)&gt;',re.VERBOSE)
url = urllib.urlopen('http://pgp.mit.edu:11371/pks/lookup?search='+search)
codehtml = url.read()
blocks = regexB.findall(codehtml)
result=[search]
for block in blocks:
  lines = regexM.findall(block)
  for line in lines:
    if line not in result:
      result.append(line)
      val ={}
      val['value'] = unicode(line, 'utf-8')
      val['verified'] = unicode('False', 'utf-8')
      write_result("email-address", val)
      sys.stdout.flush()
