##
# This file is part of WhatWeb and may be subject to
# redistribution and commercial restrictions. Please see the WhatWeb
# web site for more information on licensing and terms of use.
# http://www.morningstarsecurity.com/research/whatweb
##
Plugin.define "WordpressSuperCache" do
author "Patrik Wallström"
version "0.1"
description "Cache functionality for Wordpress - http://wordpress.org/extend/plugins/wp-super-cache/"
examples %w| www.iis.se www.thedailyfix.com www.hollywoodgrind.com|

matches [
{:name=>"supercache comment",
:probability=>100,
:regexp=>/^<!-- Cached page generated by WP-Super-Cache on /}
]

end

