#!/usr/bin/python
# coding=utf-8

import re, urllib, sys, time, urllib2, os
from generic_transform import * 
   
e_type,e_values,params = get_from_args()

NbResult = 20
if "NbResult" in params:
  NbResult = int(params["NbResult"])
  if NbResult > 100 :
    NbResult = 100
  elif NbResult < 1:
    NbResult = 1

TimeOut = 5
if "TimeOut" in params:
  TimeOut = int(params["TimeOut"])
  if TimeOut > 30 :
    TimeOut = 30
  elif TimeOut < 1:
    TimeOut = 1

result=[]

search = urllib.quote(e_values["value"])

regexG = re.compile('<p><a\shref=\"/url\?q=(((\w{2,6})://.*?)/.*?)\">',re.VERBOSE)
regexT = re.compile('<title>(.*?)</title')
page=0
b = True

lang = ''

google = ['http://www.google.com/search?q=%40','&hl=en&lr=&ie=UTF-8&start=','&sa=N']

start = time.time()
while len(result) < NbResult and time.time()-start < TimeOut:
    if not b or time.time()-start > TimeOut:
        break

    results_web = google[0]+search+google[1]+str(page*10)+google[2]
    request_web = urllib2.Request(results_web)
    request_web.add_header('User-Agent','Mozilla/4.0 (compatible; MSIE 5.5; Windows NT 5.0)')
    opener_web = urllib2.build_opener()
    text = opener_web.open(request_web).read()
    googleUrl = [text,regexG]
    lines  = regexG.findall(text)
    for line in lines:
        if len(line)> 0:
            res =line[1]
            if res not in result:
                result.append(res)
                val = {}
                val["value"] = unicode(line[0], 'utf-8')
                write_result("url", val)
                sys.stdout.flush()
                if len(result)>=NbResult or time.time()-start > TimeOut:
                    b=False
                    break
    page += 1

if time.time()-start > TimeOut:
    write_progress(100,'% : time elapsed')

